namespace ParallelTests;

public class Tests
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void CreateArtifact()
    {
        File.WriteAllText("my-filename.txt", "Generated by test: " + TestContext.CurrentContext.Test.Name);
    }

    [Test]
    public void SumTest()
    {
        Assert.AreEqual(6, 3 + 3);
    }
    
    [Test]
    public void MultiplyTest()
    {
        Assert.AreEqual(9, 3 * 3);
    }
}

public class Testsik
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void SumTestik()
    {
        Assert.AreEqual(6, 3 + 3);
    }
    
    [Test]
    public void MultiplyTestik()
    {
        Assert.AreEqual(9, 3 * 3);
    }
}
