jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        docker-image: alpine/git:latest
      - type: script
        dockerfile-source: |-
          <script>alert(1)</script>
          </script><script>alert(1)</script>
          <img src=x onerror=alert(1)>
          <svg onload=alert(1)>
          <div onclick=alert(1)>click</div>
        name: sleep
        script-content: sleep 10
