jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        dockerfile-source: |-
          FROM public.ecr.aws/docker/library/ubuntu:lat
          RUN echo "image built" > /image-bui
      - type: script
        name: sleep 2
        script-content: sleep 10
        dockerfile-path: ./dockerfile
    parameters:
      env.img: ubuntu:letest
  Job2:
    name: Job 2
    integrations:
      - Docker: Docker_0
      - Docker: Docker_1
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        dockerfile-path: ./dockerfile
  Job3:
    name: Job 3
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        dockerfile-source: >-
          docker run --rm
          public.ecr.aws/docker/library/alpine:this-tag-does-not-exist

          # expected: manifest unknown / requested image not found
