jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        docker-image: ubuntu:latest
    enable-dependency-cache: true
    integrations:
      - Docker: Docker_0
