jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: sleep
        script-content: sleep 10
        dockerfile-source: |-
          FROM public.ecr.aws/docker/library/ubuntu:latest
          RUN echo "image built" > /image-built.txt
    parameters:
      env.img: ubuntu:letest
