jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: dockerfile
        script-content: sleep 10
        dockerfile-path: ./dockerfile
      - type: script
        name: auto
        script-content: sleep 10
        docker-image: ubuntu:latest
